using Microsoft.EntityFrameworkCore;
using DtuFitnessApi.Models;


public class ApplicationDbContext : DbContext
{
    public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
        : base(options)
    {
    }
     
    public DbSet<ClubModel> Clubs { get; set; }
    public DbSet<UserProfile> UserProfiles { get; set; }
    public DbSet<ClubMember> ClubMembers { get; set; }
    public DbSet<ExerciseLog> ExerciseLogs { get; set; }
    public DbSet<ExerciseModel> Exercises { get; set; }
    public DbSet<Metric> Metrics { get; set; }
    public DbSet<ExerciseMetric> ExerciseMetrics { get; set; }
    public DbSet<Event> Events { get; set; }
    public DbSet<Notification> Notifications { get; set; }
    public DbSet<UserNotification> UserNotifications { get; set; }



    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        modelBuilder.Entity<ClubModel>(entity =>
    {
        entity.HasKey(e => e.ClubID); // Explicitly setting ClubId as the primary key

        entity.ToTable("clubs");
        entity.Property(e => e.ClubID).ValueGeneratedOnAdd(); // Assuming ClubId is auto-generated
        entity.Property(e => e.ClubName)
            .IsRequired()
            .HasMaxLength(255);

        entity.Property(e => e.Description)
            .HasMaxLength(1000);

        entity.Property(e => e.OwnerUserId)
            .IsRequired();

        entity.Property(e => e.CreationDate).IsRequired();
        
        });

          modelBuilder.Entity<UserProfile>(entity =>
{
    entity.HasKey(e => e.IdentityUserID); // Adjusted to match the actual primary key column name

    entity.ToTable("user_profiles"); // Map to the actual table name in the database

    // Since IdentityUserID is of type GUID, you may not need ValueGeneratedOnAdd() unless it's auto-generated by the database
    entity.Property(e => e.IdentityUserID)
          .IsRequired(); // Ensure this is marked as required if it's a non-nullable field in your database

    entity.Property(e => e.Username)
          .IsRequired()
          .HasMaxLength(255);

    // Configure other properties as needed
});

    modelBuilder.Entity<ClubMember>(entity =>
        {
            entity.HasKey(e => e.ClubMemberId); // Primary key for the ClubMember entity

            // Assuming ClubId and MemberId are the foreign keys in the ClubMember entity
            entity.HasOne(cm => cm.Club) // Navigation property in ClubMember
                .WithMany(c => c.ClubMembers) // If you have a corresponding collection property in ClubModel
                .HasForeignKey(cm => cm.ClubId); // Foreign key

            entity.HasOne(cm => cm.UserProfile) // Navigation property in ClubMember
                .WithMany(up => up.ClubMembers) // If you have a corresponding collection property in UserProfile
                .HasForeignKey(cm => cm.MemberId); // Foreign key

            // Map to the actual table name in the database if it's different
            entity.ToTable("clubmembers");

            // Additional configurations...
        });

        modelBuilder.Entity<ExerciseLog>(entity =>
    {
        entity.ToTable("exercise_logs");
        entity.HasKey(e => e.LogID);
        entity.Property(e => e.ExerciseDate).IsRequired();
        entity.HasOne(d => d.UserProfile).WithMany(p => p.ExerciseLogs).HasForeignKey(d => d.UserID);
        entity.HasOne(d => d.ExerciseModel) // instead of d.Exercise
          .WithMany(p => p.ExerciseLogs)
          .HasForeignKey(d => d.ExerciseID);
    });

    modelBuilder.Entity<ExerciseModel>(entity =>
    {
        entity.ToTable("exercises");
        entity.HasKey(e => e.ExerciseID);
        entity.Property(e => e.Name).IsRequired().HasMaxLength(255);
    });

    modelBuilder.Entity<Metric>(entity =>
    {
        entity.ToTable("metrics");
        entity.HasKey(e => e.MetricID);
        entity.Property(e => e.Name).IsRequired().HasMaxLength(255);
    });

    modelBuilder.Entity<ExerciseMetric>(entity =>
{
    entity.ToTable("exercise_metrics"); // Update to use the correct table name
    entity.HasKey(e => e.ExerciseMetricID);
    entity.Property(e => e.Value).IsRequired();
    
    entity.HasOne(d => d.ExerciseLog)
          .WithMany(p => p.ExerciseMetrics) // Ensure ExerciseLog has a collection of ExerciseMetric
          .HasForeignKey(d => d.ExerciseLogID);

    entity.HasOne(d => d.Metric)
          .WithMany(p => p.ExerciseMetrics)
          .HasForeignKey(d => d.MetricID);
});

modelBuilder.Entity<Notification>(entity =>
{
    entity.ToTable("notifications");
    entity.HasKey(n => n.NotificationID);

    entity.Property(n => n.Message).HasColumnType("TEXT");

    // Relationship back to Event
    entity.HasOne(n => n.Event)
          .WithMany(e => e.Notifications)
          .HasForeignKey(n => n.EventID);

    // If using UserNotifications to track per-user notification state
    entity.HasMany(n => n.UserNotifications)
          .WithOne(un => un.Notification)
          .HasForeignKey(un => un.NotificationID);
});

modelBuilder.Entity<Event>(entity =>
{
    entity.ToTable("events");
    entity.HasKey(e => e.EventID);

    entity.Property(e => e.ClubID).IsRequired();
    entity.Property(e => e.Title).IsRequired().HasMaxLength(255);
    entity.Property(e => e.Description).HasColumnType("TEXT");
    entity.Property(e => e.EventDate).IsRequired();

    // Relationship to ClubModel
    entity.HasOne(e => e.Club)
          .WithMany(c => c.Events)
          .HasForeignKey(e => e.ClubID);

    // Assuming you have a collection of notifications in your Event model
    entity.HasMany(e => e.Notifications)
          .WithOne(n => n.Event)
          .HasForeignKey(n => n.EventID);
});

modelBuilder.Entity<UserNotification>(entity =>
{
    entity.ToTable("user_notifications"); // Correct table name
    entity.HasKey(un => un.UserNotificationID);
    
    entity.Property(un => un.IsRead).IsRequired();

    entity.HasOne(un => un.Notification)
          .WithMany(n => n.UserNotifications) // Ensure there's a collection of UserNotifications in Notification
          .HasForeignKey(un => un.NotificationID);

    entity.HasOne(un => un.User)
          .WithMany(up => up.UserNotifications) // Ensure there's a collection of UserNotifications in UserProfile
          .HasForeignKey(un => un.IdentityUserID); // Make sure this foreign key is correctly named and typed
});



    }
}

